theme: jekyll-agency

url    : "https://shridhar2104.github.io"
baseurl: "" # leave empty for user.github.io site

title      : Shridhar Kute
email      : shridhar2104@gmail.com
description: "Backend + AI Infra Engineer | RAG, Go, GraphQL, DevOps"
author     : Shridhar Kute

locale: "en-US"

analytics:
  google: # Add your GA tag later (optional)

collections:
  portfolio:

markdown: kramdown

# Use Formspree to enable contact form submission
formspree_form_path: "f/mwkdpwlv"  # Replace with your Formspree ID if available
