title: "Shridhar Kute"
tagline: "Backend & AI Infra Engineer | Go, GraphQL, RAG Systems"
url: "https://shridhar2104.github.io"
baseurl: ""  # Keep empty for user.github.io domain
lang: "en"
timezone: "Asia/Kolkata"

email: "shridhar2104@gmail.com"
github:
  username: Shridhar2104
linkedin:
  username: shridhar-kute-111a16258
